# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 01:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0003_auto_20170630_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='get_topic_entries',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_logs.Topic'),
        ),
    ]
